version: "3.8"
services:
  blog_mysql:
    image: mysql:8.0.35
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - "/home/docker_volume/mysql/data:/var/lib/mysql"
      - "/home/docker_volume/mysql/init:/docker-entrypoint-initdb.d"
      - "/home/docker_volume/mysql/conf:/etc/mysql/conf.d"
    networks:
      - blog_networks
  blog_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog
    ports:
      - "8081:8081"
    networks:
      - blog_networks
    depends_on:
      - blog_mysql
  blog_nginx:
    image: nginx:1.26.1
    container_name: nginx
    ports:
      - "80:80"
      - "81:81"
    volumes:
      - "/home/docker_volume/nginx/conf/nginx.conf:/etc/nginx/nginx.conf"
      - "/home/docker_volume/nginx/html:/usr/share/nginx/html"
      - "/home/docker_volume/nginx/conf/conf.d:/etc/nginx/conf.d"
      - "/home/docker_volume/nginx/logs:/var/log/nginx"
      - "/home/docker_volume/nginx/logs/run:/var/run"
    networks:
      - blog_networks
    depends_on:
      - blog_server
networks:
  blog_networks:
    name: ayo_blog



